### ISSUE TITLE
Dynamic Step Views

### ISSUE THREAD

**Issue by eds123** [zombocom/wicked#232]
A product has multiple categories and each category has multiple fields.

I'm wondering if there would be a way to define the steps dynamically based on each category name?

`steps :category1, :category2, :category3`

I read your section about dynamic steps, however I don't have predefined names for each step. The issue I have is wicked looks for corresponding views with the same name as each step.

**Comment by schneems** [comment]
> The issue I have is wicked looks for corresponding views with the same name as each step.

What exactly do you want to happen? A product come into the wizard, you call product.steps and it returns `[:setup_step, :add_step, :confirm_step]` but you don't want to render `setup_step.html` etc. ?

**Comment by rssluca** [comment]
Hi. I think that's what he meant, and I am after the same solution. I have a form template saved as JSONB and would like to render it dynamically (the form is created using formbuilder and tabs)

**Comment by marcamillion** [comment]
@eds123 & @rssluca did you guys ever find a solution to do this?

I want to do something similar....I am doing a reconciliation of inventory at different locations (i.e. how much of each product is currently left). So each step in my wizard would be dependent on the amount of products are available in each location. i.e. 1 location can have 10 different products, each have different amounts of inventory.

So the wizard for Location 1, would have 10 steps (where 1 step reflects 1 product), but when the user goes to Location 2, there may be only 5 products so the wizard should know that and only present steps for each of those 5 products.

Is that possible using the Wicked gem?

**Comment by rssluca** [comment]
@marcamillion did not end up using wicked.. I just embedded all forms and used bootstrap tabs.

**Comment by eds123** [comment]
@marcamillion sorry no I didn't find a solution with this gem. I ended up implementing my own "Wizard"

**Comment by onslauth** [comment]
@eds123, @rssluca & @marcamillion 

I found a way to render a specific template and use dynamic steps, without any changes needed to the gem.

I build the dynamic steps with the following code in the controller:
```
prepend_before_action :set_steps

...

def show
  case steps
  when :first
    options = { } # let wicked wizard try find a view template called "first"
  else
    options = { template: "some/path" } # specify the view template to use for unhandled steps
  end
  render_wizard nil, options
end

...

def set_steps
  my_dynamic_steps = [ "one", "two is here", "three or more" ]
  self.steps = [ ]
  my_dynamic_steps.each do |s|
    self.steps << s.parameterize.underscore.to_sym
  end
end
```

This would all go into the controller where you have included wicked wizard. In the set_steps you can dynamically add the steps to the self.steps array.
Then in the show method you can let it automatically try find the view template by setting `options = { }` or handling each step in the case statement.

@schneems This is what they were trying to do I expect. I think you can close this issue if you add this to the wiki or readme. Hope this helps.

**Comment by aliahmed922** [comment]
Looks like a common issue, I've submitted #259 PR for this one. It solves the problem that you guys are facing. Let me know thoughts pls.

**Comment by chawes13** [comment]
When one of my steps contains a forward slash (e.g., `vanilla / chocolate`), it looks like the `options[:template]` argument is getting overridden.

**Comment by schneems** [comment]
You need to be extremely careful passing anything to `render`. If you allow user-submitted values to get to that method then you've introduced a directory traversal into your website. That's why Wicked examples use pre-generated step names.

I mentioned this in the PR but i'll say here, you can arbitrarily render a template with:

```ruby
jump_to(:your_erb_template_name) 
render_wizard
```

Effectively in wicked step names are just template names. If you're doing something really complicated and building a state machine for a survey, it might be easier to not build on top of wicked depending on how much customization you need.

**Comment by aliahmed922** [comment]
I agree to the fact that passing anything to `render` method must be examined carefully first for its usage. But I'm still wondering that why wicked would provide a such constraint to have the steps pre-defined with their individual steps. Because if, for a reason, we'd want to leverage it to solve a problem even in a complicated scenario and it does fulfil it then why not go with wicked. 

I just simply managed to build a large survey system in one of my app using wicked and the same common template approach.

**Comment by schneems** [comment]
>  But I'm still wondering that why wicked would provide a such constraint to have the steps pre-defined with their individual steps

Not sure what you mean here, the only constraint is that your step name needs to match the name of a view. You have to know the view names ahead of time since they are files on disk.
