### ISSUE TITLE
Question: Is it possible to pass data through wizard for query string?

### ISSUE THREAD

**Issue by LJ-03** [zombocom/wicked#279]
I'm a noob at development still, but I want to know if each data sent through each step of the wizard can eventually land on a search page at the end of the wizard.

Eg.

Step 1. Colour = Red
Step 2. Price = Under $100
Step 3. Condition = Brand New

Leads to Search index results with filters: [Red] [<$100] [New]

Does that make sense? Sorry for raising this as an issue, I figured this would be better than stack overflow

**Comment by schneems** [comment]
Since web requests are stateless you'll need to store the data somewhere (like a database) or pass it to the web page and have the webpage send the extra data on the next form. Usually people use the database. This does fall outside of https://github.com/zombocom/wicked#support but hopefully that's enough to get you started.
